# This workflow runs for Pull Requests and pushes to main branch

name: CI Process

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  run_tests:
    strategy:
      matrix:
        app: [shared, dashboard, login, payment, paymentWidget]

    runs-on: ubuntu-latest
    env:
      API_BASE_URL: https://heeeeeeeeeeeeeeeeeeeeey.com

    steps:
      - uses: actions/checkout@v3

      - name: Testing ${{ matrix.app }}
        run: source scripts/github-actions-scripts.sh && test_app ${{ matrix.app }}
  
  run_lint:
    strategy:
      matrix:
        app: [shared, dashboard, login, payment, paymentWidget]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Testing ${{ matrix.app }}
        run: source scripts/github-actions-scripts.sh && lint_app ${{ matrix.app }}
